dist: xenial
language: python
sudo: false
python:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
cache:
  pip: true
install:
  - pip install tox-travis codecov black==19.3b0
script:
  - black --check .
  - tox
env:
  matrix:
    - DJANGO="4.0"
    - DJANGO="5.0"
    - DJANGO="master"
matrix:
  allow_failures:
    - python: "3.9"
      env: DJANGO="master"
    - python: "3.10"
      env: DJANGO="master"
    - python: "3.11"
      env: DJANGO="master"
    - python: "3.12"
      env: DJANGO="master"
after_success:
  - codecov
